User-create-entry - Heerak Moon
hmoon2/code-journal pull request #5
Opened 2022-12-29 19:43 UTC by hmoon2

https://user-images.githubusercontent.com/113075380/210004430-c8124e41-ef62-4cab-92a6-d2e12d7e2d11.mp4

2022-12-29 19:50 UTC, codingcodymiller requested changes

2022-12-29 19:50 UTC, codingcodymiller commented on index.html
> +        <div class="column-full purple-background">
You should put the `purple-background` class on the `header` so it fills the whole viewport

2022-12-29 19:50 UTC, codingcodymiller commented on index.html
> +    <div class="container margin-none">
Please don't remove margin from the `container` class

2022-12-29 19:50 UTC, codingcodymiller commented on index.html
> +          <div class="column-half no-padding">
Please don't remove padding from the columns.

2022-12-29 19:50 UTC, codingcodymiller commented on index.html
> +          <div class="column-half no-padding">
Please don't remove padding from the columns.

2022-12-29 19:50 UTC, codingcodymiller commented on index.html
> +              <h4 class="padding-5">Title</h4>
this should be a `label`

2022-12-29 19:50 UTC, codingcodymiller commented on index.html
> +              <h4 class="padding-5">Photo URL</h4>
this should be a `label`

2022-12-29 19:50 UTC, codingcodymiller commented on index.html
> +        <div class="row padding-10 column-full button-right">
No one element should be both a `row` and a `column`. Give this `row` a child with the `column-full` class.

2022-12-29 19:50 UTC, codingcodymiller commented on css/styles.css
> +  width: 440px;
There should be no `px` width set on anything except the `container` class.

2022-12-29 19:50 UTC, codingcodymiller commented on css/styles.css
> +    width: 900px;
There should be no `px` width set on anything except the `container` class.

2022-12-29 19:50 UTC, codingcodymiller commented on css/styles.css
> +  }
There should be no `px` width set on anything except the `container` class.

2022-12-29 19:50 UTC, codingcodymiller commented on css/styles.css
> +}
There should be no `px` width set on anything except the `container` class.

2022-12-29 19:50 UTC, codingcodymiller commented on css/styles.css
> +}
There should be no `px` width set on anything except the `container` class.

2022-12-29 19:50 UTC, codingcodymiller commented on css/styles.css
> +  padding: 0;
You shouldn't do this, this is a _**really**_ major change

2022-12-29 19:50 UTC, codingcodymiller commented on css/layout.css
> +  padding: 0;
Please leave this as `padding: 0 1.5rem;`

2022-12-30 00:06 UTC, hmoon2 commented
https://user-images.githubusercontent.com/113075380/210022606-b6c85d51-77ef-44e5-98df-cb796aba83cb.mp4

2022-12-30 00:10 UTC, codingcodymiller approved these changes

2022-12-30 00:14 UTC, merged